# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(500, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/img/icon-settings.ico"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settingsDialog.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(settingsDialog)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 10, 500, 481))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 481))
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 481))
        self.tabWidget.setStyleSheet("QTabWidget::pane { top:20px; border:none; }\n"
                                     'QTabBar::tab:first { color:#333333; background:transparent; font-family:"微软雅黑"; font-size:14px; padding-left:-9px; padding-right:-9px; width:105px; height:30px; margin-left:0px; margin-right:40px; }\n'
                                     "QTabBar::tab:last { color:#333333; background:transparent; font-family:\"微软雅黑\"; font-size:14px; padding-left:-9px; padding-right:-9px; width:75px; height:30px; margin-left:0px; margin-right:40px; }\n"
                                     "QTabBar::tab:selected, QTabBar::tab:hover { color:#618BE5; background:transparent; font-family:\"微软雅黑\"; font-size:14px; border-bottom:2px solid #618BE5;}\n"
                                     "QTabWidget::tab-bar { alignment: left; top:10px; left:30px; }")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.basicSetEntry = QtWidgets.QWidget()
        self.basicSetEntry.setObjectName("basicSetEntry")
        self.munuSets_text = QtWidgets.QLabel(self.basicSetEntry)
        self.munuSets_text.setGeometry(QtCore.QRect(25, 10, 91, 31))
        self.munuSets_text.setObjectName("munuSets_text")
        self.gridLayoutWidget = QtWidgets.QWidget(self.basicSetEntry)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 201, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.menuSets = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.menuSets.setContentsMargins(15, 10, 0, 0)
        self.menuSets.setObjectName("menuSets")
        self.m1_a1_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m1_a1_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_a1_t.setObjectName("m1_a1_t")
        self.menuSets.addWidget(self.m1_a1_t, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem1, 9, 1, 1, 1)
        self.m2_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m2_t.setStyleSheet("font: 11pt \"新宋体\";")
        self.m2_t.setObjectName("m2_t")
        self.menuSets.addWidget(self.m2_t, 4, 0, 1, 1)
        self.m3_a1_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m3_a1_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m3_a1_t.setObjectName("m3_a1_t")
        self.menuSets.addWidget(self.m3_a1_t, 8, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem2, 7, 1, 1, 1)
        self.m1_a2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m1_a2.setText("")
        self.m1_a2.setObjectName("m1_a2")
        self.menuSets.addWidget(self.m1_a2, 2, 2, 1, 1)
        self.m3_a2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m3_a2.setEnabled(False)
        self.m3_a2.setText("")
        self.m3_a2.setChecked(True)
        self.m3_a2.setObjectName("m3_a2")
        self.menuSets.addWidget(self.m3_a2, 9, 2, 1, 1)
        self.m3_a1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m3_a1.setEnabled(False)
        self.m3_a1.setText("")
        self.m3_a1.setChecked(True)
        self.m3_a1.setObjectName("m3_a1")
        self.menuSets.addWidget(self.m3_a1, 8, 2, 1, 1)
        self.m2_a1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m2_a1.setEnabled(True)
        self.m2_a1.setText("")
        self.m2_a1.setChecked(True)
        self.m2_a1.setObjectName("m2_a1")
        self.menuSets.addWidget(self.m2_a1, 5, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem3, 1, 1, 1, 1)
        self.m1_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m1_t.setStyleSheet("font: 11pt \"新宋体\";")
        self.m1_t.setObjectName("m1_t")
        self.menuSets.addWidget(self.m1_t, 0, 0, 1, 1)
        self.m1_a1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m1_a1.setEnabled(False)
        self.m1_a1.setText("")
        self.m1_a1.setChecked(True)
        self.m1_a1.setObjectName("m1_a1")
        self.menuSets.addWidget(self.m1_a1, 1, 2, 1, 1)
        self.m2_a1_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m2_a1_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m2_a1_t.setObjectName("m2_a1_t")
        self.menuSets.addWidget(self.m2_a1_t, 5, 0, 1, 1)
        self.m1_a3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m1_a3.setEnabled(False)
        self.m1_a3.setText("")
        self.m1_a3.setChecked(True)
        self.m1_a3.setObjectName("m1_a3")
        self.menuSets.addWidget(self.m1_a3, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem4, 8, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem5, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem6, 7, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem7, 2, 1, 1, 1)
        self.m1_a3_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m1_a3_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_a3_t.setObjectName("m1_a3_t")
        self.menuSets.addWidget(self.m1_a3_t, 3, 0, 1, 1)
        self.m3_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m3_t.setStyleSheet("font: 11pt \"新宋体\";")
        self.m3_t.setObjectName("m3_t")
        self.menuSets.addWidget(self.m3_t, 7, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem8, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem9, 6, 1, 1, 1)
        self.m1_a2_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m1_a2_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_a2_t.setObjectName("m1_a2_t")
        self.menuSets.addWidget(self.m1_a2_t, 2, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem10, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem11, 4, 2, 1, 1)
        self.m2_a2_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m2_a2_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m2_a2_t.setObjectName("m2_a2_t")
        self.menuSets.addWidget(self.m2_a2_t, 6, 0, 1, 1)
        self.m3_a2_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m3_a2_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m3_a2_t.setObjectName("m3_a2_t")
        self.menuSets.addWidget(self.m3_a2_t, 9, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem12, 3, 1, 1, 1)
        self.m2_a2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m2_a2.setEnabled(True)
        self.m2_a2.setText("")
        self.m2_a2.setChecked(True)
        self.m2_a2.setObjectName("m2_a2")
        self.menuSets.addWidget(self.m2_a2, 6, 2, 1, 1)
        self.m3_a3_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.m3_a3_t.setAlignment(QtCore.Qt.AlignCenter)
        self.m3_a3_t.setObjectName("m3_a3_t")
        self.menuSets.addWidget(self.m3_a3_t, 10, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menuSets.addItem(spacerItem13, 10, 1, 1, 1)
        self.m3_a3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.m3_a3.setText("")
        self.m3_a3.setChecked(True)
        self.m3_a3.setObjectName("m3_a3")
        self.menuSets.addWidget(self.m3_a3, 10, 2, 1, 1)
        self.seperator = QtWidgets.QFrame(self.basicSetEntry)
        self.seperator.setGeometry(QtCore.QRect(245, 0, 5, 450))
        self.seperator.setAutoFillBackground(False)
        self.seperator.setStyleSheet("background-color: #ccc;")
        self.seperator.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seperator.setLineWidth(1)
        self.seperator.setFrameShape(QtWidgets.QFrame.VLine)
        self.seperator.setObjectName("seperator")
        self.label_2 = QtWidgets.QLabel(self.basicSetEntry)
        self.label_2.setGeometry(QtCore.QRect(25, 390, 91, 31))
        self.label_2.setObjectName("label_2")
        self.m3_a3_2 = QtWidgets.QCheckBox(self.basicSetEntry)
        self.m3_a3_2.setGeometry(QtCore.QRect(150, 398, 56, 13))
        self.m3_a3_2.setText("")
        self.m3_a3_2.setChecked(True)
        self.m3_a3_2.setObjectName("m3_a3_2")
        self.tabWidget.addTab(self.basicSetEntry, "")
        self.savesSetEntry = QtWidgets.QWidget()
        self.savesSetEntry.setObjectName("savesSetEntry")
        self.tabWidget.addTab(self.savesSetEntry, "")

        self.retranslateUi(settingsDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Settings"))
        self.munuSets_text.setText(_translate(
            "settingsDialog", "<h2>菜单内容：</h2>"))
        self.m1_a1_t.setText(_translate("settingsDialog", "登录："))
        self.m2_t.setText(_translate("settingsDialog", "<h4>存档：</h4>"))
        self.m3_a1_t.setText(_translate("settingsDialog", "帮助："))
        self.m1_t.setText(_translate("settingsDialog", "<h4>用户：</h4>"))
        self.m2_a1_t.setText(_translate("settingsDialog", "读档："))
        self.m1_a3_t.setText(_translate("settingsDialog", "设置："))
        self.m3_t.setText(_translate("settingsDialog", "<h4>帮助：</h4>"))
        self.m1_a2_t.setText(_translate("settingsDialog", "注册："))
        self.m2_a2_t.setText(_translate("settingsDialog", "存档："))
        self.m3_a2_t.setText(_translate("settingsDialog", "关于："))
        self.m3_a3_t.setText(_translate("settingsDialog", "关于插件："))
        self.label_2.setText(_translate("settingsDialog", "<h2>背景音乐：</h2>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.basicSetEntry), _translate("settingsDialog", "基础设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.savesSetEntry), _translate("settingsDialog", "存档设置"))
